// <auto-generated />
namespace FindTutor.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class launchdatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(launchdatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202008131124274_launch-database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
