//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindTutor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Http.Cors;

    public partial class Image
    {
        public int Id { get; set; }

        public string Title { get; set; }

        [Display(Name = "Upload Image")]
        public string Path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
